apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: notes-backend
  labels:
    app: notes-app
    environment: production
    tier: backend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Auto-scaling configuration
        autoscaling.knative.dev/minScale: "2"
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/target: "80"
        autoscaling.knative.dev/metric: "concurrency"
        
        # Resource configuration
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
        
        # VPC Connector (for Cloud SQL private IP)
        run.googleapis.com/vpc-access-connector: "notes-vpc-connector"
        run.googleapis.com/vpc-access-egress: "private-ranges-only"
        
        # Execution environment
        run.googleapis.com/execution-environment: "gen2"
        
        # Session affinity (sticky sessions)
        run.googleapis.com/sessionAffinity: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: notes-backend-sa@PROJECT_ID.iam.gserviceaccount.com
      
      containers:
      - name: notes-backend
        image: gcr.io/PROJECT_ID/notes-backend:latest
        
        ports:
        - name: http1
          containerPort: 3001
        
        env:
        - name: NODE_ENV
          value: "production"
        - name: BACKEND_PORT
          value: "3001"
        - name: CLUSTER_MODE
          value: "false"
        - name: ENABLE_PERFORMANCE_LOGGING
          value: "true"
        - name: ENABLE_METRICS_COLLECTION
          value: "true"
        - name: ENABLE_WEB_VITALS_LOGGING
          value: "true"
        
        # Secrets from Secret Manager
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: latest
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: session-secret
              key: latest
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-url
              key: latest
        
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        
        # Liveness probe
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        # Startup probe
        startupProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
